import type { z } from "zod";

/**
 * Map of job names to their Zod payload schemas.
 * Generated by zod-asyncapi from AsyncAPI specs.
 */
export type JobsMap = Record<string, z.ZodTypeAny>;

/**
 * Options for triggering a worker job.
 */
export interface TriggerOptions {
  /** Idempotency key to prevent duplicate executions */
  idempotencyKey?: string;
  /** Delay before job execution (ISO 8601 duration or Date) */
  delay?: string | Date;
  /** Maximum number of retry attempts */
  maxRetries?: number;
  /** Custom metadata/headers */
  metadata?: Record<string, string>;
}

/**
 * Result of triggering a job.
 */
export interface TriggerResult {
  /** Unique identifier for the triggered job run */
  id: string;
}

/**
 * Type-safe worker client interface.
 * Implementations: workers-client-trigger, workers-client-warpstream
 *
 * @typeParam T - Jobs map from AsyncAPI-generated types
 */
export interface WorkerClient<T extends JobsMap> {
  /**
   * Trigger a worker job.
   * @param jobName - Job name (type-safe from Jobs map)
   * @param payload - Job payload (validated against schema)
   * @param options - Optional trigger options
   */
  trigger<K extends keyof T & string>(
    jobName: K,
    payload: z.infer<T[K]>,
    options?: TriggerOptions,
  ): Promise<TriggerResult>;

  /**
   * Trigger multiple jobs in a batch.
   * @param jobName - Job name (type-safe from Jobs map)
   * @param payloads - Array of job payloads
   * @param options - Optional trigger options (applied to all jobs)
   */
  triggerBatch<K extends keyof T & string>(
    jobName: K,
    payloads: z.infer<T[K]>[],
    options?: TriggerOptions,
  ): Promise<TriggerResult[]>;

  /**
   * Disconnect the client and release resources.
   */
  disconnect(): Promise<void>;
}

