/**
 * Offset primitives for the Durable Streams Protocol (Section 6).
 *
 * Offsets are opaque, case-sensitive, lexicographically sortable tokens.
 * They MUST NOT contain `,`, `&`, `=`, `?`, or `/` (URL query-syntax reserved).
 * Servers SHOULD keep them under 256 characters.
 */

/** Sentinel offset representing the beginning of a stream. */
export const OFFSET_BEGINNING = "-1";

/** Sentinel offset representing the current tail (skip all existing data). */
export const OFFSET_NOW = "now";

/** Maximum offset length the protocol recommends (Section 6). */
export const MAX_OFFSET_LENGTH = 256;

const FORBIDDEN_OFFSET_CHARS = /[,&=?/]/;

/**
 * True if `s` is a structurally valid offset string.
 * Does NOT check that the offset exists in a real stream — that's a storage
 * concern. This is purely a syntactic gate for 400 Bad Request.
 *
 * Sentinel values (`-1`, `now`) are considered valid offsets.
 */
export function isValidOffset(s: unknown): s is string {
  if (typeof s !== "string") return false;
  if (s.length === 0) return false;
  if (s.length > MAX_OFFSET_LENGTH) return false;
  if (FORBIDDEN_OFFSET_CHARS.test(s)) return false;
  return true;
}

/**
 * Classifies an offset string as a sentinel or a concrete offset.
 * Returns `"start"` for `-1`, `"now"` for `now`, or `null` otherwise.
 */
export function isSentinel(s: string): "start" | "now" | null {
  if (s === OFFSET_BEGINNING) return "start";
  if (s === OFFSET_NOW) return "now";
  return null;
}

/**
 * Byte-wise lexicographic comparison. Returns negative, 0, or positive
 * following the usual Array.prototype.sort convention.
 *
 * Per Section 6: "clients MAY compare offsets lexicographically to determine
 * ordering." Sentinel values should be resolved before comparison; comparing
 * them directly to concrete offsets is not meaningful.
 */
export function compareOffsets(a: string, b: string): number {
  if (a < b) return -1;
  if (a > b) return 1;
  return 0;
}

/**
 * Asserts that an offset generated by a storage implementation is not a
 * reserved sentinel value. Per Section 6: "Server implementations MUST NOT
 * generate these strings as actual stream offsets."
 *
 * Storage adapters should call this when producing new offsets in development
 * or tests to catch bugs early.
 */
export function isReservedSentinelLiteral(s: string): boolean {
  return s === OFFSET_BEGINNING || s === OFFSET_NOW;
}
