import type { z } from "zod";

/**
 * Map of topic names to their Zod message schemas.
 * Generated by zod-asyncapi from AsyncAPI specs.
 */
export type TopicsMap = Record<string, z.ZodTypeAny>;

/**
 * Options for sending a message to a topic.
 */
export interface SendOptions {
  /** Message key for partitioning */
  key?: string | Buffer | null;
  /** Explicit partition number */
  partition?: number;
  /** Custom message headers */
  headers?: Record<string, string | Buffer>;
  /** Message timestamp */
  timestamp?: string;
}

/**
 * Type-safe Kafka client interface.
 * Implementations: kafka-client-kafkajs, kafka-client-warpstream
 *
 * @typeParam T - Topics map from AsyncAPI-generated types
 * @typeParam TProducer - Underlying producer type (for escape hatch)
 */
export interface KafkaClient<T extends TopicsMap, TProducer = unknown> {
  /**
   * Send a single message to a topic.
   * @param topic - Topic name (type-safe from Topics map)
   * @param message - Message payload (validated against schema)
   * @param options - Optional send options
   */
  send<K extends keyof T & string>(
    topic: K,
    message: z.infer<T[K]>,
    options?: SendOptions,
  ): Promise<void>;

  /**
   * Send multiple messages to a topic in a batch.
   * @param topic - Topic name (type-safe from Topics map)
   * @param messages - Array of message payloads
   * @param options - Optional send options (applied to all messages)
   */
  sendBatch<K extends keyof T & string>(
    topic: K,
    messages: z.infer<T[K]>[],
    options?: SendOptions,
  ): Promise<void>;

  /**
   * Disconnect the client and release resources.
   */
  disconnect(): Promise<void>;

  /**
   * Access the underlying producer for advanced use cases.
   * Type depends on the binding (e.g., kafkajs Producer).
   */
  readonly producer: TProducer;
}
